"""End-to-end tests for the high-level index-research workflow."""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from pathlib import Path

import numpy as np
from openpyxl import load_workbook
import pandas as pd
import pytest

from icapa.analytics import (
    AnalyticsPluginResult,
    AnalyticsPluginSpec,
    AnalyticsRunResult,
    AnalyticsSpec,
    ResearchAnalyticsInputs,
)
from icapa.backtesting import (
    BacktestResult,
    Calendar,
    RebalanceFrequency,
)
from icapa.data_sources import register_provider, registry
from icapa.reporting import ReportBundleSpec, ReportFormat
from icapa.research import (
    IndexDefinition,
    ResearchSimulationSpec,
    ResearchSpec,
    ResearchStatus,
    ResearchWorkspace,
    UnsafeCacheReuseError,
)
from icapa.portfolio_construction import (
    Artifact,
    ArtifactOutput,
    CORE_TARGET_WEIGHTS,
    IndexRecipe,
    StageCacheScope,
    StageDescriptor,
    StageNode,
    StageRequirements,
    StageResult,
)
from icapa.workspace import (
    CacheMode,
    CacheOptions,
    CacheStage,
    IdentityError,
    automatic_digest,
    dataframe_content_digest,
)


_PROVIDER_NAME = "research_workflow_synthetic"
_CALLS = {"universe": 0, "market": 0}
_IDENTITY_CALLS = {"provider": 0}
_RICH_CONTEXT_CALLS = {"methodology": 0}


def _runtime_sample(*parts: str) -> str:
    """Assemble redaction fixtures without storing sensitive-shaped literals."""
    return "".join(parts)


class _SyntheticProvider:
    """Stable offline data whose snapshot identity is generated by the provider."""

    def research_data_identity(self, *, capability, request):
        _IDENTITY_CALLS["provider"] += 1
        return {
            "dataset": "synthetic_research",
            "revision": 1,
            "capability": capability,
        }

    def load_universe(
        self,
        universe_id,
        reference_date,
        effective_date,
        **kwargs,
    ):
        _CALLS["universe"] += 1
        weights = (
            np.array([0.45, 0.35, 0.20])
            if pd.Timestamp(effective_date).month == 6
            else np.array([0.35, 0.40, 0.25])
        )
        return pd.DataFrame(
            {
                "instrument_id": ["A", "B", "C"],
                "name": ["Alpha", "Beta", "Gamma"],
                "country": ["US", "US", "CA"],
                "industry": ["Technology", "Industrials", "Technology"],
                "shares": [100.0, 120.0, 80.0],
                "free_float": [0.9, 0.8, 0.95],
                "price": [20.0, 30.0, 25.0],
                "currency": ["USD", "USD", "CAD"],
                "base_currency": ["USD", "USD", "USD"],
                "fx_rate": [1.0, 1.0, 0.75],
                "market_cap": [1800.0, 2880.0, 1425.0],
                "benchmark_weight": weights,
                "reference_date": [pd.Timestamp(reference_date)] * 3,
                "effective_date": [pd.Timestamp(effective_date)] * 3,
            }
        )

    def load_daily_market_data(
        self,
        instrument_ids,
        start_date,
        end_date,
        **kwargs,
    ):
        _CALLS["market"] += 1
        rows = []
        for date_offset, business_date in enumerate(
            pd.bdate_range(start_date, end_date)
        ):
            for instrument_offset, instrument_id in enumerate(instrument_ids):
                rows.append(
                    {
                        "instrument_id": instrument_id,
                        "business_date": business_date,
                        "price_return": (
                            0.0002
                            + 0.00005 * instrument_offset
                            + 0.00001 * (date_offset % 5)
                        ),
                        "gross_dividend": 0.00001,
                        "net_dividend": 0.000008,
                        "market_cap": (
                            1_000_000.0
                            * (instrument_offset + 1)
                            * (1.0 + 0.001 * date_offset)
                        ),
                    }
                )
        return pd.DataFrame.from_records(rows)


@dataclass(frozen=True)
class _SnapshotMethodology:
    universe_id: str = "SYNTHETIC"
    universe_provider_name: str = _PROVIDER_NAME

    def research_data_identity(self):
        provider = registry.get(self.universe_provider_name)
        return provider.research_data_identity(
            capability="load_universe",
            request={"universe_id": self.universe_id},
        )

    def execute(self, context):
        provider = registry.resolve(
            "load_universe",
            self.universe_provider_name,
        )
        frame = provider.load_universe(
            universe_id=self.universe_id,
            reference_date=context.reference_date,
            effective_date=context.effective_date,
        )
        frame["index_weight"] = frame["benchmark_weight"]
        context.universe_id = self.universe_id
        context.set_dataframe(frame)
        return context


@dataclass(frozen=True)
class _SensitiveParameterMethodology(_SnapshotMethodology):
    url: str = (
        "postgresql://private-user:private-password@internal-host/research"
    )
    note: str = "password=private-password"


@dataclass(frozen=True)
class _ReportTarget:
    field: str
    direction: str
    target: float


@dataclass(frozen=True)
class _PrivateReportSolver:
    token: str = "private-solver-token"


@dataclass(frozen=True)
class _NestedReportMethodology(_SnapshotMethodology):
    factor_tilts: dict[str, float] = field(
        default_factory=lambda: {"quality-score": 0.7, "value": 0.3}
    )
    targets: tuple[_ReportTarget, ...] = field(
        default_factory=lambda: (
            _ReportTarget("quality", "minimum", 0.6),
            _ReportTarget("carbon", "maximum", 0.2),
        )
    )
    universe_provider_parameters: dict[str, str] = field(
        default_factory=lambda: {
            "password": "private-provider-password",
            "dataset": "private-provider-dataset",
        }
    )
    solver: _PrivateReportSolver = field(
        default_factory=_PrivateReportSolver,
        repr=False,
    )
    connection_url: str = (
        "postgresql://private-user:private-password@internal-host/research"
    )
    api_key: str = "private-api-key"
    access_key: str = "private-access-key"
    endpoint: str = "internal-api.example.invalid"
    service_uri: str = "custom://internal-service/private"
    serviceUri: str = "custom://camel-service/private"
    connectionUriValue: str = "custom://camel-connection/private"
    maturity: float = 7.5
    security_count: int = 6
    accounting_method: str = "daily_accrual"
    glide_path: str = "linear"
    account: str = "private-service-account"
    file_path: str = "/private/research/input.csv"
    connection_path: str = "/private/connections/provider.json"
    authorization: str = "Bearer manifest-super-secret"
    pem: str = _runtime_sample(
        "-----BEGIN PRIVATE ", "KEY-----\nmanifest-private-key"
    )
    comment: str = "Basic bWFuaWZlc3QtYmFzaWMtc2VjcmV0"
    location_hint: str = _runtime_sample(
        "/", "Users/private/research/source.csv"
    )
    storage_settings: dict[str, object] = field(
        default_factory=lambda: {
            "path": "/private/root",
            "data_path": "/private/data",
            "workspace_path": "/private/workspace",
            "input_path": "/private/input",
            "output_path": "/private/output",
            "template_path": "/private/template",
            "cache_path": "/private/cache",
            "artifact_path": "/private/artifact",
            "database": "private-database",
            "schema": "private-schema",
            "server": "private-server",
            "warehouse": "private-warehouse",
            "auth": "private-auth",
            "oauth": "private-oauth",
            "schema_version": "2026.1",
            "glide_path": "nested-linear",
            "transition_path": "staged",
        }
    )
    note: str = "api_key=private-note-api-key"
    description: str = "custom://private-user:private-pass@private-host/path"
    business_notes: dict[str, str] = field(
        default_factory=lambda: {
            "note_01": "access_key=assigned-access-key-secret",
            "note_02": "aws_access_key_id=assigned-aws-key-secret",
            "note_03": "authorization=Basic assigned-auth-secret",
            "note_04": "endpoint=https://internal-endpoint.invalid/private",
            "note_05": "user=assigned-user-secret",
            "note_06": _runtime_sample(
                "Loaded /", "Users/private/research/embedded.csv"
            ),
            "note_07": _runtime_sample(
                "path=/", "Users/private/research/assigned.csv"
            ),
            "note_08": _runtime_sample(
                "Loaded C:", r"\Users\private\research\embedded.csv"
            ),
            "note_09": "Loaded ~/private/research/embedded.csv",
            "note_10": "aws_secret_access_key=assigned-aws-secret-key",
            "note_11": "query=select * from private_query_table",
            "note_12": (
                "Provider failed: SELECT exposure FROM "
                "private_exposure_table"
            ),
        }
    )


@dataclass(frozen=True)
class _OpaqueMethodology:
    universe_id: str = "SYNTHETIC"
    universe_provider_name: str = _PROVIDER_NAME

    def execute(self, context):
        provider = registry.resolve(
            "load_universe",
            self.universe_provider_name,
        )
        frame = provider.load_universe(
            universe_id=self.universe_id,
            reference_date=context.reference_date,
            effective_date=context.effective_date,
        )
        frame["index_weight"] = frame["benchmark_weight"]
        context.universe_id = self.universe_id
        context.set_dataframe(frame)
        return context


@dataclass(frozen=True)
class _ProvenanceSnapshotMethodology(_SnapshotMethodology):
    def execute(self, context):
        result = super().execute(context)
        result.provenance.record_provider_call(
            {
                "provider": {
                    "provider_name": self.universe_provider_name,
                    "capability": "load_universe",
                },
                "request_digest": automatic_digest(
                    {
                        "universe_id": self.universe_id,
                        "reference_date": result.reference_date,
                        "effective_date": result.effective_date,
                    }
                ),
                "content_digest": dataframe_content_digest(result.cons),
            }
        )
        return result


@dataclass(frozen=True)
class _RichContextSnapshotMethodology(_SnapshotMethodology):
    def execute(self, context):
        _RICH_CONTEXT_CALLS["methodology"] += 1
        result = super().execute(context)
        result.set_dataframe(
            pd.DataFrame(
                {
                    "instrument_id": ["A", "B", "C"],
                    "custom_factor": [1.25, -0.50, 0.75],
                    "custom_signal": ["include", "review", "include"],
                }
            )
        )
        result.daily = pd.DataFrame(
            {
                "instrument_id": ["A", "B", "C"],
                "business_date": [
                    result.reference_date,
                    result.reference_date,
                    result.reference_date,
                ],
                "custom_daily_signal": [0.10, 0.20, 0.30],
            }
        ).set_index(["instrument_id", "business_date"])
        result.diagnostics["custom_research"] = {
            "threshold": 0.25,
            "selection_reason": "factor and signal review",
            "checks": ["weights", "coverage"],
        }
        result.provenance.record_provider_call(
            {
                "provider": {
                    "provider_name": self.universe_provider_name,
                    "capability": "load_universe",
                },
                "request_digest": automatic_digest(
                    {
                        "reference_date": result.reference_date,
                        "effective_date": result.effective_date,
                    }
                ),
                "content_digest": dataframe_content_digest(result.cons),
            }
        )
        return result


class _RecipeWeightStage:
    calls = 0

    @property
    def descriptor(self):
        return StageDescriptor(
            "test.recipe_weight_stage",
            cache_scope=StageCacheScope.CONTENT,
        )

    @property
    def requirements(self):
        return StageRequirements()

    @property
    def outputs(self):
        return (ArtifactOutput(CORE_TARGET_WEIGHTS),)

    def canonical_configuration(self):
        return {"weights": [0.4, 0.6]}

    def run(self, inputs, runtime):
        type(self).calls += 1
        weights = pd.Series(
            [0.4, 0.6],
            index=pd.Index(["A", "B"], name="instrument_id"),
            name="index_weight",
        )
        return StageResult(
            {
                CORE_TARGET_WEIGHTS: Artifact.from_value(
                    CORE_TARGET_WEIGHTS,
                    weights,
                )
            }
        )


@pytest.fixture(autouse=True)
def _synthetic_provider():
    _CALLS.update(universe=0, market=0)
    _IDENTITY_CALLS["provider"] = 0
    register_provider(_PROVIDER_NAME, _SyntheticProvider(), replace=True)
    yield
    registry.unregister(_PROVIDER_NAME)


def _calendar():
    return Calendar.from_dates(
        [
            {
                "reference_date": "2026-05-22",
                "effective_date": "2026-06-01",
            },
            {
                "reference_date": "2026-06-19",
                "effective_date": "2026-07-01",
            },
        ]
    )


def _spec(methodology, *, cache=None, report=False):
    return ResearchSpec(
        definition=IndexDefinition(
            index_id="SYNTHETIC_RESEARCH_INDEX",
            name="Synthetic Research Index",
            base_currency="USD",
            methodology=methodology,
            rebalance_frequency=RebalanceFrequency.MONTHLY,
        ),
        calendar=_calendar(),
        simulation=ResearchSimulationSpec(
            market_data_provider_name=_PROVIDER_NAME,
            start_date="2026-06-01",
            end_date="2026-07-10",
        ),
        analytics=AnalyticsSpec.legacy_parity(),
        cache=cache or CacheOptions.off(),
        report=(
            ReportBundleSpec(
                name="synthetic_research",
                formats=(ReportFormat.JSON,),
                overwrite=True,
            )
            if report
            else None
        ),
        label="baseline",
        tags=("demo", "research"),
    )


def test_high_level_pipeline_defaults_to_uncached_lightweight_results(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace.open("high_level_default")

    run = workspace.run(_spec(_SnapshotMethodology(), report=True))

    assert _CALLS == {"universe": 2, "market": 2}
    assert run.manifest.status == "complete"
    assert len(run.manifest.execution_id) == 32
    assert len(run.manifest.definition_fingerprint) == 64
    assert len(run.manifest.result_fingerprint) == 64
    assert run.simulation is not None
    assert run.simulation.holdings.empty
    assert run.simulation.asset_returns.empty
    assert (
        run.simulation.metadata["calculation_mode"]
        == "calendar_month_partitions"
    )
    assert run.analytics is not None
    assert len(run.review_status) == 2
    assert set(run.review_status["status"]) == {"complete"}
    assert run.report is not None
    assert run.report.path.is_dir()
    assert {
        item["input_type"] for item in run.manifest.input_digests
    } == {
        "analytics_calculation_inputs",
        "source_daily_market_data",
    }

    coverage = workspace.coverage()
    assert coverage.iloc[0]["label"] == "baseline"
    assert coverage.iloc[0]["tags"] == ("demo", "research")
    assert coverage.iloc[0]["artifact_count"] > 0
    assert coverage.iloc[0]["research_status"] == "draft"
    assert workspace.latest() == run.manifest
    assert workspace.open_run(run.manifest_ref) == run.manifest
    assert workspace.verify().ok
    assert workspace.rebuild_catalog().registered == 1
    assert workspace.prune().dry_run
    assert workspace.set_status(run, ResearchStatus.IN_REVIEW) is (
        ResearchStatus.IN_REVIEW
    )
    assert workspace.get_status(run) is ResearchStatus.IN_REVIEW

    workspace.invalidate(run)
    assert workspace.latest() is None
    assert workspace.list() == ()
    assert workspace.list(include_invalidated=True) == (run.manifest_ref,)


@pytest.mark.parametrize("recipe_wrapped", [False, True])
def test_high_level_report_projects_nested_public_methodology_parameters(
    tmp_path,
    monkeypatch,
    recipe_wrapped,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    methodology = _NestedReportMethodology()
    executable = (
        IndexRecipe.from_methodology(
            methodology,
            recipe_id="nested_report_recipe",
            recipe_version="1",
        )
        if recipe_wrapped
        else methodology
    )
    workspace = ResearchWorkspace.open(
        f"nested_report_{'recipe' if recipe_wrapped else 'direct'}"
    )
    spec = replace(
        _spec(executable),
        report=ReportBundleSpec(
            name="nested_methodology_parameters",
            formats=(ReportFormat.XLSX, ReportFormat.JSON),
            overwrite=True,
        ),
    )

    run = workspace.run(spec)

    assert run.report is not None
    workbook = load_workbook(run.report.files["report.xlsx"], data_only=True)
    sheet = workbook["Methodology Parameters"]
    rows = list(sheet.iter_rows(values_only=True))
    header_position = next(
        position
        for position, row in enumerate(rows)
        if tuple(row[:2]) == ("parameter", "value")
    )
    parameters = {
        str(row[0]): row[1]
        for row in rows[header_position + 1 :]
        if row[0] is not None
    }
    assert parameters["factor_tilts.quality_score"] == 0.7
    assert parameters["targets.item_001.field"] == "quality"
    assert parameters["targets.item_001.target"] == 0.6
    assert parameters["targets.item_002.direction"] == "maximum"
    assert parameters["maturity"] == 7.5
    assert parameters["security_count"] == 6
    assert parameters["accounting_method"] == "daily_accrual"
    assert parameters["glide_path"] == "linear"
    assert parameters["pem"] == "[REDACTED]"
    assert parameters["comment"] == "[REDACTED]"
    assert parameters["location_hint"] == "[REDACTED]"
    assert parameters["storage_settings.schema_version"] == "2026.1"
    assert parameters["storage_settings.glide_path"] == "nested-linear"
    assert parameters["storage_settings.transition_path"] == "staged"
    assert parameters["note"] == "[REDACTED]"
    assert parameters["description"] == "[REDACTED]"
    for position in range(1, 13):
        assert (
            parameters[f"business_notes.note_{position:02d}"]
            == "[REDACTED]"
        )
    assert ("recipe_id" in parameters) is recipe_wrapped
    assert "service_uri" not in parameters
    assert "serviceUri" not in parameters
    assert "connectionUriValue" not in parameters
    assert "account" not in parameters
    assert "file_path" not in parameters
    assert "connection_path" not in parameters
    assert "authorization" not in parameters
    for private_nested_parameter in (
        "path",
        "data_path",
        "workspace_path",
        "input_path",
        "output_path",
        "template_path",
        "cache_path",
        "artifact_path",
        "database",
        "schema",
        "server",
        "warehouse",
        "auth",
        "oauth",
    ):
        assert (
            f"storage_settings.{private_nested_parameter}"
            not in parameters
        )
    assert not any(
        restricted in name.casefold()
        for name in parameters
        for restricted in (
            "provider_name",
            "provider_parameters",
            "solver",
            "connection",
            "api_key",
            "access_key",
            "endpoint",
            "password",
            "token",
            "url",
        )
    )

    definition_request = run.manifest.request["definition"]
    assert "methodology_parameters" in definition_request
    assert "methodology_report_parameters" in definition_request
    assert (
        definition_request["methodology_parameters"]
        != definition_request["methodology_report_parameters"]
    )
    assert "universe_provider_parameters" in repr(
        definition_request["methodology_parameters"]
    )
    manifest_text = Path(run.manifest_ref.path).read_text(encoding="utf-8")
    assert "identity_digest" in manifest_text

    rendered_values = "\n".join(
        str(cell)
        for worksheet in workbook.worksheets
        for row in worksheet.iter_rows(values_only=True)
        for cell in row
        if cell is not None
    )
    json_values = "\n".join(
        path.read_text(encoding="utf-8")
        for path in run.report.path.rglob("*.json")
    )
    for secret in (
        "private-solver-token",
        "private-provider-password",
        "private-provider-dataset",
        "private-api-key",
        "private-access-key",
        "private-user",
        "private-password",
        "internal-host",
        "internal-api.example.invalid",
        "internal-service",
        "camel-service",
        "camel-connection",
        "private-note-api-key",
        "private-pass",
        "private-host",
        "private-service-account",
        "/private/research/input.csv",
        "/private/connections/provider.json",
        "manifest-super-secret",
        "manifest-private-key",
        "bWFuaWZlc3QtYmFzaWMtc2VjcmV0",
        _runtime_sample("/", "Users/private/research/source.csv"),
        "/private/root",
        "/private/data",
        "/private/workspace",
        "/private/input",
        "/private/output",
        "/private/template",
        "/private/cache",
        "/private/artifact",
        "private-database",
        "private-schema",
        "private-server",
        "private-warehouse",
        "private-auth",
        "private-oauth",
        "assigned-access-key-secret",
        "assigned-aws-key-secret",
        "assigned-auth-secret",
        "internal-endpoint.invalid",
        "assigned-user-secret",
        _runtime_sample("/", "Users/private/research/embedded.csv"),
        _runtime_sample("/", "Users/private/research/assigned.csv"),
        _runtime_sample("C:", r"\Users\private\research\embedded.csv"),
        "~/private/research/embedded.csv",
        "assigned-aws-secret-key",
        "private_query_table",
        "private_exposure_table",
    ):
        if secret != "private-provider-dataset":
            assert secret not in manifest_text
        assert secret not in rendered_values
        assert secret not in json_values
    assert "identity_digest" not in rendered_values
    assert "identity_digest" not in json_values

    loaded = workspace.load_run(run.manifest.execution_id)
    restored_report = workspace.write_report(
        loaded,
        spec=ReportBundleSpec(
            name="rehydrated_nested_methodology_parameters",
            formats=(ReportFormat.XLSX, ReportFormat.JSON),
            overwrite=True,
        ),
    )
    restored_workbook = load_workbook(
        restored_report.files["report.xlsx"],
        data_only=True,
    )
    restored_rows = list(
        restored_workbook["Methodology Parameters"].iter_rows(
            values_only=True
        )
    )
    restored_header = next(
        position
        for position, row in enumerate(restored_rows)
        if tuple(row[:2]) == ("parameter", "value")
    )
    restored_parameters = {
        str(row[0]): row[1]
        for row in restored_rows[restored_header + 1 :]
        if row[0] is not None
    }
    assert restored_parameters == parameters

    def methodology_name(book):
        overview_rows = list(book["Overview"].iter_rows(values_only=True))
        header = next(
            position
            for position, row in enumerate(overview_rows)
            if tuple(row[:2]) == ("field", "value")
        )
        return {
            str(row[0]): row[1]
            for row in overview_rows[header + 1 :]
            if row[0] is not None
        }["methodology_name"]

    assert methodology_name(restored_workbook) == methodology_name(workbook)
    restored_json = "\n".join(
        path.read_text(encoding="utf-8")
        for path in restored_report.path.rglob("*.json")
    )
    assert "identity_digest" not in restored_json
    for secret in (
        "private-api-key",
        "private-access-key",
        "private-provider-dataset",
        "internal-api.example.invalid",
        "internal-service",
        "manifest-super-secret",
        "manifest-private-key",
        "bWFuaWZlc3QtYmFzaWMtc2VjcmV0",
        _runtime_sample("/", "Users/private/research/source.csv"),
        "/private/root",
        "private-database",
        "private-schema",
        "private-server",
        "private-warehouse",
        "private-auth",
        "private-oauth",
        "assigned-access-key-secret",
        "assigned-aws-key-secret",
        "assigned-auth-secret",
        "internal-endpoint.invalid",
        "assigned-user-secret",
        _runtime_sample("/", "Users/private/research/embedded.csv"),
        _runtime_sample("/", "Users/private/research/assigned.csv"),
        _runtime_sample("C:", r"\Users\private\research\embedded.csv"),
        "~/private/research/embedded.csv",
        "assigned-aws-secret-key",
        "private_query_table",
        "private_exposure_table",
    ):
        assert secret not in restored_json


def test_report_parameter_projection_stops_on_recursive_mappings():
    from icapa.research.runners.identity import _report_parameter_mapping

    recursive: dict[str, object] = {}
    recursive["self"] = recursive

    assert _report_parameter_mapping({"public": recursive}) == {
        "public": {"self": {}}
    }


def test_requested_report_failure_marks_the_execution_failed_and_sanitized(
    tmp_path,
    monkeypatch,
):
    import icapa.research.workspace as workflow_module

    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace.open("report_failure_audit")

    def fail_report(*args, **kwargs):
        del args, kwargs
        raise RuntimeError(
            "postgresql://private-user:private-password@internal-host/db"
        )

    monkeypatch.setattr(
        workflow_module,
        "write_report_bundle",
        fail_report,
    )

    with pytest.raises(RuntimeError):
        workspace.run(_spec(_SnapshotMethodology(), report=True))

    failed = workspace.latest()
    assert failed is not None
    assert failed.status == "failed"
    assert failed.result_fingerprint is not None
    assert failed.artifacts
    assert failed.request["report"]["name"] == "synthetic_research"
    assert failed.failure == {
        "error_type": "RuntimeError",
        "message": (
            "Execution failed. The original exception is intentionally "
            "not persisted because it may contain sensitive provider data."
        ),
    }
    manifest_text = Path(
        workspace.list(include_invalidated=True)[0].path
    ).read_text(encoding="utf-8")
    for sensitive_text in (
        "postgresql://",
        "private-user",
        "private-password",
        "internal-host",
    ):
        assert sensitive_text not in manifest_text


def test_methodology_and_attribute_connection_values_never_enter_manifest(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace.open("manifest_value_sanitization")
    spec = ResearchSpec(
        definition=IndexDefinition(
            index_id="SAFE_MANIFEST_INDEX",
            methodology=_SensitiveParameterMethodology(),
            attributes={
                "status": "SELECT private_value FROM internal_schema.table",
                "description": (
                    "postgresql://nested-user:nested-password@"
                    "nested-host/research"
                ),
            },
        ),
        calendar=_calendar(),
        analytics=None,
    )

    run = workspace.run(spec)

    manifest_text = Path(run.manifest_ref.path).read_text(encoding="utf-8")
    for sensitive_text in (
        "postgresql://",
        "private-user",
        "private-password",
        "internal-host",
        "nested-user",
        "nested-password",
        "nested-host",
        "SELECT private_value",
        "internal_schema",
    ):
        assert sensitive_text not in manifest_text


def test_default_research_analytics_accepts_canonical_review_date_columns(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace("canonical_analytics")
    spec = replace(
        _spec(_SnapshotMethodology()),
        analytics=AnalyticsSpec.standard_research(),
    )

    run = workspace.run(spec)

    assert run.analytics is not None
    assert "selection_reasons" in run.analytics.plugin_results
    assert run.manifest.status == "complete"


def test_verifiable_reuse_skips_review_and_simulation_recalculation(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    cache = CacheOptions(
        stage_modes={
            CacheStage.REVIEWS: CacheMode.REUSE,
            CacheStage.SIMULATION: CacheMode.REUSE,
        }
    )
    workspace = ResearchWorkspace("high_level_reuse")
    spec = _spec(_SnapshotMethodology(), cache=cache)

    first = workspace.run(spec)
    calls_after_first = dict(_CALLS)
    second = workspace.run(spec)
    subset = workspace.run(
        ResearchSpec(
            definition=spec.definition,
            calendar=Calendar.from_dates(
                [
                    {
                        "reference_date": "2026-05-22",
                        "effective_date": "2026-06-01",
                    }
                ]
            ),
            analytics=None,
            cache=cache,
        )
    )

    assert calls_after_first == {"universe": 2, "market": 2}
    assert _CALLS == calls_after_first
    assert not first.cache_diagnostics
    assert not second.cache_diagnostics
    assert {
        item["stage"]: item["mode"]
        for item in second.manifest.cache_decisions
    }["reviews"] == "reuse"
    assert second.simulation.metadata["cache_source"] == "workspace"
    assert {
        item["input_type"] for item in second.manifest.input_digests
    } == {
        "analytics_calculation_inputs",
        "reviews_snapshot",
        "simulation_snapshot",
        "source_daily_market_data",
    }
    assert (
        second.manifest.result_fingerprint
        == first.manifest.result_fingerprint
    )
    assert set(second.review_status["cache_source"]).issubset(
        {"memory", "disk"}
    )
    assert set(subset.review_status["cache_source"]).issubset(
        {"memory", "disk"}
    )
    assert (
        subset.manifest.definition_fingerprint
        == first.manifest.definition_fingerprint
    )


def test_public_catalog_rebuild_restores_read_only_cache_bindings(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace.open("public_catalog_rebuild")
    reusable = _spec(
        _SnapshotMethodology(),
        cache=CacheOptions.reuse(),
    )

    workspace.run(reusable)
    calls_after_reuse = dict(_CALLS)
    workspace.workspace_path.joinpath("catalog.sqlite").unlink()

    reopened = ResearchWorkspace.open("public_catalog_rebuild")
    rebuilt = reopened.rebuild_catalog()
    assert not rebuilt.errors
    assert rebuilt.registered == 1
    assert rebuilt.artifacts > 0
    assert rebuilt.bindings > 0

    read_only = reopened.run(
        replace(reusable, cache=CacheOptions.read_only())
    )

    assert read_only.manifest.status == "complete"
    assert _CALLS == calls_after_reuse
    assert reopened.verify().ok


def test_review_cache_preserves_provider_provenance_inputs(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace.open("review_provenance")
    cache = CacheOptions(
        stage_modes={CacheStage.REVIEWS: CacheMode.REUSE}
    )
    spec = ResearchSpec(
        definition=IndexDefinition(
            index_id="REVIEW_PROVENANCE_INDEX",
            methodology=_ProvenanceSnapshotMethodology(),
        ),
        calendar=_calendar(),
        analytics=None,
        cache=cache,
    )

    first = workspace.run(spec)
    calls_after_first = dict(_CALLS)
    second = workspace.run(spec)

    assert _CALLS == calls_after_first
    for run in (first, second):
        provider_inputs = [
            item
            for item in run.manifest.input_digests
            if item["input_type"] == "load_universe"
        ]
        assert len(provider_inputs) == 2
        assert all(item["content_digest"] for item in provider_inputs)
    assert (
        first.manifest.result_fingerprint
        == second.manifest.result_fingerprint
    )


def test_read_only_review_reuse_never_calls_legacy_identity_hook(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    missing_workspace = ResearchWorkspace.open("legacy_review_read_only_missing")
    missing_spec = ResearchSpec(
        definition=IndexDefinition(
            index_id="LEGACY_REVIEW_READ_ONLY_MISSING",
            methodology=_SnapshotMethodology(),
        ),
        calendar=_calendar(),
        analytics=None,
        cache=CacheOptions(
            stage_modes={CacheStage.REVIEWS: CacheMode.READ_ONLY}
        ),
    )
    identity_calls_before_missing = _IDENTITY_CALLS["provider"]
    with pytest.raises(UnsafeCacheReuseError):
        missing_workspace.run(missing_spec)
    assert _IDENTITY_CALLS["provider"] == identity_calls_before_missing
    assert missing_workspace.latest().status == "failed"

    workspace = ResearchWorkspace.open("legacy_review_read_only")
    definition = IndexDefinition(
        index_id="LEGACY_REVIEW_READ_ONLY",
        methodology=_SnapshotMethodology(),
    )
    reusable = ResearchSpec(
        definition=definition,
        calendar=_calendar(),
        analytics=None,
        cache=CacheOptions(
            stage_modes={CacheStage.REVIEWS: CacheMode.REUSE}
        ),
    )
    workspace.run(reusable)
    identity_calls = _IDENTITY_CALLS["provider"]
    universe_calls = _CALLS["universe"]

    read_only = workspace.run(
        replace(
            reusable,
            cache=CacheOptions(
                stage_modes={CacheStage.REVIEWS: CacheMode.READ_ONLY}
            ),
        )
    )

    assert _IDENTITY_CALLS["provider"] == identity_calls
    assert _CALLS["universe"] == universe_calls
    assert set(read_only.review_status["cache_source"]).issubset(
        {"memory", "disk"}
    )


def test_high_level_workspace_accepts_native_recipe_and_persists_stage_cache(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    _RecipeWeightStage.calls = 0
    recipe = IndexRecipe(
        nodes=(StageNode("weights", _RecipeWeightStage()),)
    )
    cache = CacheOptions(
        stage_modes={CacheStage.REVIEWS: CacheMode.REUSE}
    )
    spec = ResearchSpec(
        definition=IndexDefinition(
            index_id="RECIPE_INDEX",
            methodology=recipe,
            rebalance_frequency=RebalanceFrequency.MONTHLY,
        ),
        calendar=_calendar(),
        analytics=None,
        cache=cache,
    )
    workspace = ResearchWorkspace.open("native_recipe")

    first = workspace.run(spec)
    second = workspace.run(spec)

    assert _RecipeWeightStage.calls == 2
    pd.testing.assert_frame_equal(first.backtest.weights, second.backtest.weights)
    assert all(
        context.diagnostics["index_recipe"]["recipe_digest"]
        for context in second.backtest.reviews.values()
    )
    assert any(
        item["input_type"] == "recipe_stage_artifact"
        for item in second.manifest.input_digests
    )


def test_opaque_methodology_never_claims_safe_review_reuse(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace("opaque_research")
    reuse = CacheOptions(
        stage_modes={CacheStage.REVIEWS: CacheMode.REUSE}
    )
    run = workspace.run(
        ResearchSpec(
            definition=IndexDefinition(
                "OPAQUE_INDEX",
                _OpaqueMethodology(),
            ),
            calendar=_calendar(),
            cache=reuse,
            analytics=None,
        )
    )

    review_decision = next(
        item
        for item in run.manifest.cache_decisions
        if item["stage"] == "reviews"
    )
    assert review_decision["requested_mode"] == "reuse"
    assert review_decision["mode"] == "off"
    assert run.backtest.metadata.workspace_name is None
    assert any("review" in item for item in run.cache_diagnostics)

    read_only = CacheOptions(
        stage_modes={CacheStage.REVIEWS: CacheMode.READ_ONLY}
    )
    with pytest.raises(UnsafeCacheReuseError):
        workspace.run(
            ResearchSpec(
                definition=IndexDefinition(
                    "OPAQUE_INDEX",
                    _OpaqueMethodology(),
                ),
                calendar=_calendar(),
                cache=read_only,
                analytics=None,
            )
        )
    assert workspace.latest().status == "failed"


@pytest.mark.parametrize(
    "mode",
    (CacheMode.REUSE, CacheMode.REFRESH, CacheMode.READ_ONLY),
)
def test_unfingerprintable_methodology_rejects_every_non_off_cache_mode(
    tmp_path,
    monkeypatch,
    mode,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))

    def execute(self, context):
        del self
        context.set_dataframe(
            pd.DataFrame(
                {
                    "instrument_id": ["A", "B"],
                    "index_weight": [0.4, 0.6],
                    "benchmark_weight": [0.5, 0.5],
                }
            )
        )
        return context

    dynamic_type = type(
        "DynamicMethodology",
        (),
        {
            "__module__": "builtins",
            "execute": execute,
        },
    )
    workspace = ResearchWorkspace.open(
        f"unfingerprintable_{mode.value}"
    )
    spec = ResearchSpec(
        definition=IndexDefinition(
            "UNFINGERPRINTABLE_INDEX",
            dynamic_type(),
        ),
        calendar=_calendar(),
        analytics=None,
        cache=CacheOptions(
            stage_modes={CacheStage.REVIEWS: mode}
        ),
    )

    with pytest.raises(UnsafeCacheReuseError, match="stable executable"):
        workspace.run(spec)
    assert workspace.latest().status == "failed"


def test_unfingerprintable_methodology_can_run_with_cache_off(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))

    def execute(self, context):
        del self
        context.set_dataframe(
            pd.DataFrame(
                {
                    "instrument_id": ["A"],
                    "index_weight": [1.0],
                    "benchmark_weight": [1.0],
                }
            )
        )
        return context

    dynamic_type = type(
        "DynamicMethodology",
        (),
        {
            "__module__": "builtins",
            "execute": execute,
        },
    )
    workspace = ResearchWorkspace.open("unfingerprintable_off")
    run = workspace.run(
        ResearchSpec(
            definition=IndexDefinition(
                "UNFINGERPRINTABLE_OFF_INDEX",
                dynamic_type(),
            ),
            calendar=_calendar(),
            analytics=None,
        )
    )

    assert run.manifest.status == "complete"
    assert run.backtest.weights["index_weight"].eq(1.0).all()


def test_preflight_identity_failure_still_writes_sanitized_manifest(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace.open("preflight_failure")
    spec = ResearchSpec(
        definition=IndexDefinition(
            index_id="PREFLIGHT_FAILURE_INDEX",
            methodology=_SnapshotMethodology(),
            attributes={"unsupported": object()},
        ),
        calendar=_calendar(),
        analytics=None,
    )

    with pytest.raises(IdentityError):
        workspace.run(spec)

    latest = workspace.latest()
    assert latest is not None
    assert latest.status == "failed"
    assert latest.request == {"phase": "automatic_preflight"}
    assert latest.failure is not None
    assert "object at 0x" not in str(latest.failure)


def test_governance_labels_do_not_change_calculation_fingerprints(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace.open("governance_identity")
    definition = IndexDefinition(
        index_id="GOVERNANCE_INDEX",
        methodology=_SnapshotMethodology(),
        rebalance_frequency=RebalanceFrequency.MONTHLY,
    )
    baseline = workspace.run(
        ResearchSpec(
            definition=definition,
            calendar=_calendar(),
            analytics=None,
            label="baseline",
            tags=("baseline",),
            status=ResearchStatus.APPROVED,
        )
    )
    candidate = workspace.run(
        ResearchSpec(
            definition=definition,
            calendar=_calendar(),
            analytics=None,
            label="candidate",
            tags=("candidate",),
            status=ResearchStatus.DRAFT,
        )
    )

    assert (
        baseline.manifest.request_fingerprint
        == candidate.manifest.request_fingerprint
    )
    assert (
        baseline.manifest.result_fingerprint
        == candidate.manifest.result_fingerprint
    )
    assert baseline.manifest.request["label"] == "baseline"
    assert candidate.manifest.request["label"] == "candidate"
    assert workspace.get_status(baseline) is ResearchStatus.APPROVED
    assert workspace.get_status(candidate) is ResearchStatus.DRAFT


def test_simulation_only_provider_changes_request_not_index_definition(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    alternate_provider_name = "research_workflow_alternate_market"
    register_provider(
        alternate_provider_name,
        _SyntheticProvider(),
        replace=True,
    )
    workspace = ResearchWorkspace.open("simulation_provider_identity")
    baseline_spec = _spec(_SnapshotMethodology())
    try:
        baseline = workspace.run(baseline_spec)
        candidate = workspace.run(
            replace(
                baseline_spec,
                simulation=replace(
                    baseline_spec.simulation,
                    market_data_provider_name=alternate_provider_name,
                ),
            )
        )
    finally:
        registry.unregister(alternate_provider_name)

    assert baseline.manifest.definition_fingerprint == (
        candidate.manifest.definition_fingerprint
    )
    assert baseline.manifest.request_fingerprint != (
        candidate.manifest.request_fingerprint
    )


def test_high_level_analytics_cache_skips_repeat_plugin_execution(
    tmp_path,
    monkeypatch,
):
    import icapa.research.runners.analytics as workflow_module

    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    calls = {"analytics": 0}
    original = workflow_module.run_analytics_plugins

    def counted(*args, **kwargs):
        calls["analytics"] += 1
        return original(*args, **kwargs)

    monkeypatch.setattr(
        workflow_module,
        "run_analytics_plugins",
        counted,
    )
    cache = CacheOptions(
        stage_modes={CacheStage.ANALYTICS: CacheMode.REUSE}
    )
    spec = _spec(_SnapshotMethodology(), cache=cache)
    workspace = ResearchWorkspace.open("analytics_reuse")

    first = workspace.run(spec)
    second = workspace.run(spec)

    assert calls["analytics"] == 1
    assert first.analytics is not None
    assert second.analytics is not None
    assert next(
        item
        for item in second.manifest.cache_decisions
        if item["stage"] == "analytics"
    )["mode"] == "reuse"
    analytics_record = next(
        item
        for item in second.manifest.input_digests
        if item["input_type"] == "analytics_calculation_inputs"
    )
    assert analytics_record["cache_source"] == "workspace"
    assert (
        first.manifest.result_fingerprint
        == second.manifest.result_fingerprint
    )


def test_high_level_analytics_inputs_are_executed_and_identify_cache(
    tmp_path,
    monkeypatch,
):
    import icapa.research.runners.analytics as workflow_module

    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    calls = {"analytics": 0}
    original = workflow_module.run_analytics_plugins

    def counted(*args, **kwargs):
        calls["analytics"] += 1
        return original(*args, **kwargs)

    monkeypatch.setattr(
        workflow_module,
        "run_analytics_plugins",
        counted,
    )
    cache = CacheOptions(
        stage_modes={CacheStage.ANALYTICS: CacheMode.REUSE}
    )
    analytics_spec = AnalyticsSpec(
        profile="constraint_only",
        plugins=(AnalyticsPluginSpec("constraint_diagnostics"),),
    )
    first_inputs = ResearchAnalyticsInputs(
        constraint_diagnostics=pd.DataFrame(
            [
                {
                    "effective_date": "2026-06-01",
                    "name": "maximum_weight",
                    "value": 0.45,
                    "lower": 0.0,
                    "upper": 0.50,
                }
            ]
        )
    )
    changed_inputs = ResearchAnalyticsInputs(
        constraint_diagnostics=pd.DataFrame(
            [
                {
                    "effective_date": "2026-06-01",
                    "name": "maximum_weight",
                    "value": 0.40,
                    "lower": 0.0,
                    "upper": 0.50,
                }
            ]
        )
    )
    base = replace(
        _spec(_SnapshotMethodology(), cache=cache),
        analytics=analytics_spec,
        analytics_inputs=first_inputs,
    )
    workspace = ResearchWorkspace.open("analytics_explicit_inputs")

    first = workspace.run(base)
    second = workspace.run(base)
    changed = workspace.run(
        replace(base, analytics_inputs=changed_inputs)
    )

    assert calls["analytics"] == 2
    assert first.analytics is not None
    assert second.analytics is not None
    assert changed.analytics is not None
    assert first.analytics.tables()[
        "constraint_diagnostics.detail"
    ].iloc[0]["achieved_value"] == pytest.approx(0.45)
    assert changed.analytics.tables()[
        "constraint_diagnostics.detail"
    ].iloc[0]["achieved_value"] == pytest.approx(0.40)
    assert (
        first.manifest.request_fingerprint
        == second.manifest.request_fingerprint
    )
    assert (
        first.manifest.request_fingerprint
        != changed.manifest.request_fingerprint
    )


def test_plugin_metadata_survives_completed_run_rehydration(
    tmp_path,
    monkeypatch,
):
    import icapa.research.runners.analytics as workflow_module

    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    analytics_spec = AnalyticsSpec(
        profile="metadata_persistence",
        plugins=(AnalyticsPluginSpec("metadata_probe"),),
    )
    expected_metadata = {
        "period_count": 2,
        "method": "linked",
    }

    def metadata_result(*args, **kwargs):
        del args, kwargs
        return AnalyticsRunResult(
            spec=analytics_spec,
            plugin_results={
                "metadata_probe": AnalyticsPluginResult(
                    metadata=expected_metadata,
                )
            },
            legacy_result=None,
            diagnostics=(),
        )

    monkeypatch.setattr(
        workflow_module,
        "run_analytics_plugins",
        metadata_result,
    )
    workspace = ResearchWorkspace.open("plugin_metadata_persistence")
    run = workspace.run(
        replace(
            _spec(_SnapshotMethodology()),
            analytics=analytics_spec,
        )
    )

    loaded = workspace.load_run(run.manifest_ref)

    assert loaded.analytics is not None
    assert dict(
        loaded.analytics.plugin_results["metadata_probe"].metadata
    ) == expected_metadata


def test_completed_runs_rehydrate_for_cross_session_comparison_and_report(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace.open("persisted_run_rehydration")
    _RICH_CONTEXT_CALLS["methodology"] = 0
    baseline = workspace.run(_spec(_RichContextSnapshotMethodology()))
    candidate = workspace.run(
        replace(
            _spec(_RichContextSnapshotMethodology()),
            label="candidate",
            tags=("candidate",),
        )
    )
    calls_after_calculation = dict(_CALLS)
    methodology_calls_after_calculation = _RICH_CONTEXT_CALLS[
        "methodology"
    ]

    reopened = ResearchWorkspace.open("persisted_run_rehydration")
    loaded_baseline = reopened.load_run(
        baseline.manifest.execution_id
    )
    loaded_candidate = reopened.rehydrate(candidate.manifest_ref)
    comparison = reopened.compare(
        loaded_baseline,
        [loaded_candidate],
    )
    report = reopened.write_report(
        loaded_baseline,
        comparison=comparison,
        spec=ReportBundleSpec(
            name="rehydrated_comparison",
            formats=(ReportFormat.XLSX, ReportFormat.JSON),
            overwrite=True,
        ),
    )

    assert _CALLS == calls_after_calculation
    assert (
        _RICH_CONTEXT_CALLS["methodology"]
        == methodology_calls_after_calculation
    )
    assert reopened.open_run(baseline.manifest_ref) == baseline.manifest
    assert loaded_baseline.manifest == baseline.manifest
    assert loaded_baseline.definition.display_name == (
        baseline.definition.display_name
    )
    pd.testing.assert_frame_equal(
        loaded_baseline.backtest.weights,
        baseline.backtest.weights.sort_index(),
    )
    for effective_date, original_context in baseline.backtest.reviews.items():
        restored_context = loaded_baseline.backtest.reviews[effective_date]
        pd.testing.assert_frame_equal(
            restored_context.cons,
            original_context.cons.sort_index(),
        )
        pd.testing.assert_frame_equal(
            restored_context.daily,
            original_context.daily.sort_index(),
        )
        assert restored_context.diagnostics == original_context.diagnostics
        assert tuple(restored_context.provenance.records) == tuple(
            original_context.provenance.records
        )
        assert restored_context.universe_id == original_context.universe_id
        assert restored_context.calendar is not None
        pd.testing.assert_frame_equal(
            restored_context.calendar.dates,
            _calendar().dates,
        )
    assert loaded_baseline.simulation is not None
    assert baseline.simulation is not None
    pd.testing.assert_frame_equal(
        loaded_baseline.simulation.daily,
        baseline.simulation.daily.sort_index(),
    )
    assert loaded_baseline.analytics is not None
    assert loaded_baseline.analytics.legacy_result is not None
    assert dict(
        loaded_baseline.analytics.plugin_results[
            "legacy_parity"
        ].metrics
    ) == dict(
        baseline.analytics.plugin_results["legacy_parity"].metrics
    )
    assert not comparison.weight_differences.empty
    assert report.files["report.xlsx"].is_file()
    workbook = load_workbook(report.files["report.xlsx"], data_only=True)
    assert "Comparison Summary" in workbook.sheetnames
    assert "Research Summary" in workbook.sheetnames
    expected_report_root = reopened.workspace_path.joinpath(
        "runs",
        loaded_baseline.manifest.definition_fingerprint,
        "reports",
    )
    assert report.path.parent == expected_report_root
    assert report.path.is_relative_to(expected_report_root)
    assert not reopened.reports_path.joinpath(report.path.name).exists()
    latest_names = {
        workbook["Latest Holdings"].cell(row=row, column=2).value
        for row in range(4, 7)
    }
    assert latest_names == {"Alpha", "Beta", "Gamma"}


def test_persisted_result_artifacts_have_canonical_row_order(
    tmp_path,
    monkeypatch,
):
    monkeypatch.setenv("ICAPA_WORKSPACE_ROOT", str(tmp_path))
    workspace = ResearchWorkspace.open("canonical_result_artifacts")
    run = workspace.run(_spec(_SnapshotMethodology()))
    assert run.simulation is not None

    reordered_reviews = {}
    for effective_date, context in reversed(tuple(run.backtest.reviews.items())):
        reordered = context.copy()
        reordered._df = context.cons.iloc[::-1].copy()
        reordered_reviews[effective_date] = reordered
    reordered_backtest = BacktestResult(
        weights=run.backtest.weights.iloc[::-1],
        reviews=reordered_reviews,
        metadata=run.backtest.metadata,
    )
    reordered_simulation = replace(
        run.simulation,
        daily=run.simulation.daily.iloc[::-1],
        holdings=run.simulation.holdings.iloc[::-1],
        rebalances=run.simulation.rebalances.iloc[::-1],
        asset_returns=run.simulation.asset_returns.iloc[::-1],
        weight_snapshots=run.simulation.weight_snapshots.iloc[::-1],
    )

    original = workspace._save_result_artifacts(
        run.backtest,
        run.simulation,
        run.analytics,
    )
    reordered = workspace._save_result_artifacts(
        reordered_backtest,
        reordered_simulation,
        run.analytics,
    )

    assert {
        item.artifact_type: item.content_digest for item in original
    } == {
        item.artifact_type: item.content_digest for item in reordered
    }
