"""Extensible constrained portfolio-optimization API."""

from .constraints import (
    LinearConstraintSpec,
    NonlinearConstraintSpec,
    group_constraint_specs,
    tracking_error_constraint,
    turnover_constraint,
    weight_bounds,
)
from .entropy_dual import (
    EGMUElasticSolver,
    EGMUNewtonSolver,
    EGMUResult,
    egmu_elastic,
    egmu_newton,
)
from .entropy_projection import (
    EGMUConstrainedElasticSolver,
    EGMUProjectionResult,
    EGMUProjectionSolver,
    egmu_project_linear,
    egmu_project_elastic,
    relative_entropy,
)
from .objectives import minimum_variance_objective, squared_distance_objective
from .models import (
    CallableObjectiveSpec,
    ConstraintEvaluation,
    ConstraintReport,
    ConstraintStatus,
    LinearObjectiveSpec,
    MinimumVarianceObjectiveSpec,
    ModelSolver,
    ObjectiveSpec,
    OptimizationModelSpec,
    PortfolioSolverModelAdapter,
    SolverCapability,
    SquaredDistanceObjectiveSpec,
    WeightVariableSpec,
    evaluate_problem_constraints,
)
from .portfolio_model import (
    FieldExposureConstraintSpec,
    GroupWeightConstraintSpec,
    LiquidityConstraintSpec,
    PortfolioModelSpec,
)
from .problem import OptimizationError, OptimizationProblem, OptimizationResult
from .qp import (
    FeasibilityReport,
    FeasibilityStatus,
    ModelSolveResult,
    OSQPBackend,
    OptionalSolverDependencyError,
    SolverRouter,
    check_linear_feasibility,
)
from .risk import (
    CovarianceEstimate,
    CovarianceEstimator,
    CovarianceMissingDataPolicy,
    CovarianceShrinkageTarget,
    FactorCovarianceEstimator,
    ResolvedReturnWindow,
    ReturnWindowKind,
    ReturnWindowSpec,
    SampleCovarianceEstimator,
    ShrinkageCovarianceEstimator,
    estimate_covariance_for_window,
)
from .solvers import PortfolioSolver, ScipySLSQPSolver, solve_slsqp

__all__ = [
    "CallableObjectiveSpec",
    "ConstraintEvaluation",
    "ConstraintReport",
    "ConstraintStatus",
    "CovarianceEstimate",
    "CovarianceEstimator",
    "CovarianceMissingDataPolicy",
    "CovarianceShrinkageTarget",
    "EGMUConstrainedElasticSolver",
    "EGMUElasticSolver",
    "EGMUNewtonSolver",
    "EGMUProjectionResult",
    "EGMUProjectionSolver",
    "EGMUResult",
    "FactorCovarianceEstimator",
    "FeasibilityReport",
    "FeasibilityStatus",
    "FieldExposureConstraintSpec",
    "GroupWeightConstraintSpec",
    "LinearConstraintSpec",
    "LinearObjectiveSpec",
    "LiquidityConstraintSpec",
    "MinimumVarianceObjectiveSpec",
    "ModelSolver",
    "ModelSolveResult",
    "NonlinearConstraintSpec",
    "OSQPBackend",
    "ObjectiveSpec",
    "OptionalSolverDependencyError",
    "OptimizationError",
    "OptimizationModelSpec",
    "OptimizationProblem",
    "OptimizationResult",
    "PortfolioSolver",
    "PortfolioSolverModelAdapter",
    "PortfolioModelSpec",
    "ResolvedReturnWindow",
    "ReturnWindowKind",
    "ReturnWindowSpec",
    "SampleCovarianceEstimator",
    "ShrinkageCovarianceEstimator",
    "ScipySLSQPSolver",
    "SolverCapability",
    "SolverRouter",
    "SquaredDistanceObjectiveSpec",
    "WeightVariableSpec",
    "check_linear_feasibility",
    "egmu_elastic",
    "egmu_newton",
    "egmu_project_linear",
    "egmu_project_elastic",
    "estimate_covariance_for_window",
    "evaluate_problem_constraints",
    "group_constraint_specs",
    "minimum_variance_objective",
    "relative_entropy",
    "solve_slsqp",
    "squared_distance_objective",
    "tracking_error_constraint",
    "turnover_constraint",
    "weight_bounds",
]
